name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simplae JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Max
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"